### ISSUE TITLE
Min and Target SDK

### ISSUE THREAD

**Issue by ghost** [LibChecker/LibChecker#1389]
Hey,

i saw that the App has Target SDK on 35 and Minimum SDK on 24 and I wanted to ask if you could make Minimum SDK to 26/28/29/31? (Higher is always better) I would appreciate that!

A higher Minimum SDK version implies that your app supports fewer Android versions, minimizing compatibility issues. Because higher SDK means also Versions which are supported better. It makes the work easier. because Android 12 (SDK 31) is the last version that receives security patches. Further more, the less minSdk, the more internal compatibility layers, techniques etc. For example, lower SDK versions require v1/v2 signing, have somewhat different optimization levels, etc.

**Comment by zhaobozhen** [comment]
The application will run different logic depending on the system version of the device container it is running on. Compatible code for a lower version of the system does not affect or slow down a higher version of the system. libChecker's current minSdkVersion is 24, and the reason we dropped support for Android 5/6 was really because there were a lot of issues with those platforms that were difficult for apps to solve. But I think a minimum of 24 is still reasonable for now.
