### ISSUE TITLE
Is there any way to continue using Material 2 as an optional toggle like it was prior to 2.2.10 with Material 3 (You)?

### ISSUE THREAD

**Issue by User198263321** [LibChecker/LibChecker#293]
I personally do not like the look and feel of Material 3 (You) as a whole. It also doesn't match my Android 11 device's UI as it's mostly material 2 based. Did you deprecate the old UI, or would it be easy to keep in the code?

**Comment by zhaobozhen** [comment]
It was because of the high cost of maintaining two sets of themes at the same time that I decided to remove the old UI design. The fact is that UI designs are constantly updated and old designs are always replaced by new ones. And I'm not following the Material 3 design documentation exactly, I'll have some of my own design tweaks. I'll try to make LibChecker's UI better looking and more functional.😉
